execute: lab10_unit_test.o lab10.o
	g++ -Wall -g -o execute lab10.o lab10_unit_test.o

lab06test_program: lab10_unit_test.cpp
	g++ -Wall -g -c lab10_unit_test.cpp

lab06: lab10.cpp
	g++ -Wall -g -c lab10.cpp	

clean:
	rm *.o *test