all: execute

execute: vaultmain.o vaultclass.o 
	g++ -Wall -g -o execute vaultmain.o vaultclass.o

exampleObj: vaultmain.cpp  
	g++ -Wall -g -c vaultmain.cpp

exampleClassObj: vaultclass.cpp 
	g++ -Wall -g -c vaultclass.cpp	