execute: lab06_unit_test.o lab06.o
	g++ -Wall -g -o execute lab06.o lab06_unit_test.o

lab06test_program: lab06_unit_test.cpp
	g++ -Wall -g -c lab06_unit_test.cpp

lab06: lab06.cpp
	g++ -Wall -g -c lab06.cpp	

clean:
	rm *.o *test